export const T = {
  bg: "var(--qc-bg)",
  surface: "var(--qc-surface)",
  surface2: "var(--qc-surface2)",
  border: "var(--qc-border)",
  border2: "var(--qc-border2)",
  text: "var(--qc-text)",
  muted: "var(--qc-muted)",
  muted2: "var(--qc-muted2)",
  blue: "#2F81F7",
  blueD: "#1C5FAD",
  blueL: "#1C2D3F",
  green: "#3FB950",
  greenD: "#238636",
  greenL: "#1A2E21",
  red: "#F85149",
  redD: "#B91C1C",
  redL: "#2D1B1B",
  yellow: "#D29922",
  yellowL: "#2D2200",
  purple: "#A371F7",
  purpleL: "#221A3E",
  aqua: "#39D2EE",
  aquaL: "#0D2535",
  pink: "#FF7EB3",
  pinkL: "#2D1525",
  orange: "#F0883E",
  r: "8px",
  r2: "12px",
  font: "'Outfit', sans-serif",
  mono: "'IBM Plex Mono', monospace",
};

export const PRODUCTS = {
  1: { model: "WM1091SK", color: "Blue" },
  2: { model: "WM1091SK", color: "Purple" },
  3: { model: "WM891SK", color: "Aqua" },
  4: { model: "WM891SK", color: "Pink" },
};

export const COLOR_HEX = {
  Blue: T.blue,
  Purple: T.purple,
  Aqua: T.aqua,
  Pink: T.pink,
};
export const COLOR_BGL = {
  Blue: T.blueL,
  Purple: T.purpleL,
  Aqua: T.aquaL,
  Pink: T.pinkL,
};

export const ROLE_GRAD = {
  admin: "linear-gradient(135deg,#B45309,#F0883E)",
  operator: "linear-gradient(135deg,#1C5FAD,#2F81F7)",
  viewer: "linear-gradient(135deg,#1C5FAD,#2F81F7)",
};

export const CHECKPOINTS = [
  "Visual Inspection – Body Panel",
  "Dimensional Check – Door Frame",
  "Electrical Safety Test",
  "Water Leak Test",
  "Drum Balance Test",
  "Label Placement Check",
  "Color Matching",
  "Function Test – All Modes",
];

// INSPECTORS removed as per user request (Shift & Inspector fields deleted)

export const DEFECT_CATS = [
  { v: "DS01", l: "DL01 – Lecet A" },
  { v: "DS02", l: "DL02 – Lecet B" },
  { v: "DS03", l: "DL03 – Lecet C" },
  { v: "DS04", l: "DL04 – Lecet D" },
  { v: "DC05", l: "DC05 – Camera Berdebu" },
  { v: "DC06", l: "DC06 – Camera Tergores" },
  { v: "DC07", l: "DC07 – Camera Tidak Terdeteksi" },
  { v: "DC08", l: "DC08 – Camera Titik Hitam" },
  { v: "DC09", l: "DC09 – Camera Titik Putih" },
  { v: "DC10", l: "DC10 – Camera Flicker" },
  { v: "DC11", l: "DC11 – Camera Tidak Fokus" },
  { v: "DC12", l: "DC12 – Camera Tidak Normal" },
  { v: "DC13", l: "DC13 – Camera Dent" },
  { v: "DC14", l: "DC14 – Camera Blur" },
  { v: "DG15", l: "DG15 – Gompal A" },
  { v: "DG16", l: "DG16 – Gompal B" },
  { v: "DG17", l: "DG17 – Gompal C" },
  { v: "DG18", l: "DG18 – Gompal D" },
  { v: "DL24", l: "DL24 – LCD Pecah" },
  { v: "DL25", l: "DL25 – LCD Tidak Menyala" },
  { v: "DL26", l: "DL26 – LCD Lecet" },
  { v: "DL27", l: "DL27 – LCD Gompal" },
  { v: "DL28", l: "DL28 – LCD Redup" },
  { v: "DL29", l: "DL29 – LCD Kedip" },
  { v: "DL30", l: "DL30 – LCD Garis " },
  { v: "DL31", l: "DL31 – LCD Bias " },
  { v: "DG32", l: "DG32 – Gompal A" },
  { v: "DG33", l: "DG33 – Gompal B" },
  { v: "DG34", l: "DG34 – Gompal C" },
  { v: "DG35", l: "DG35 – Gompal D" },
];

export const mkCp = (result = "fail") =>
  CHECKPOINTS.map((c) => ({ name: c, result, value: "" }));

// SEC 3 Mitigation: Client-side authentication is fundamentally insecure.
// In a real production system, consider implementing a proper backend auth (e.g., JWT).
export const SEED_USERS = [
  {
    id: 1,
    name: "Admin QC",
    username: "admin",
    role: "admin",
    password: "admin123",
    active: true,
    created_at: "2025-01-01T00:00:00Z",
  },
  {
    id: 2,
    name: "Ahmad Operator",
    username: "ahmad",
    role: "operator",
    password: "Ahmad123op",
    active: true,
    created_at: "2025-01-02T00:00:00Z",
  },
  {
    id: 3,
    name: "Viewer Only",
    username: "viewer",
    role: "viewer",
    password: "Viewer123x",
    active: true,
    created_at: "2025-01-03T00:00:00Z",
  },
];

export const SEED_REPORTS = [
  {
    id: 1,
    product_id: 1,
    model: "WM1091SK",
    color: "Blue",
    batch_no: "B-WM1091-0001",
    production_date: "2025-03-01",
    inspection_date: "2025-03-01T08:30",
    qty_burning_in: 200,
    qty_produced: 200,
    qty_inspected: 200,
    qty_pass: 0,
    qty_fail: 4,
    qty_rework: 2,
    defect_rate: 2.0,
    defect_cat: "DC01",
    defect_loc: "Top panel",
    station: "QA",
    overall_status: "fail",
    notes: "Minor surface scratches on 4 units",
    serial_numbers: [
      "0831PN2600Y0000",
      "0831AQ2600Y0000",
      "5920BL2003Z07073",
      "5920LA2508Y00864",
    ],
    images: [],
    checkpoints: mkCp(),
    created_at: "2025-03-01T08:30:00Z",
  },
  {
    id: 2,
    product_id: 1,
    model: "WM1091SK",
    color: "Blue",
    batch_no: "B-WM1091-0002",
    production_date: "2025-03-01",
    inspection_date: "2025-03-01T13:00",
    qty_burning_in: 200,
    qty_produced: 200,
    qty_inspected: 200,
    qty_pass: 0,
    qty_fail: 7,
    qty_rework: 5,
    defect_rate: 3.5,
    defect_cat: "DC02",
    defect_loc: "Side panel",
    station: "Repair",
    overall_status: "fail",
    notes: "Color inconsistency detected",
    serial_numbers: ["SN-BL-20101", "SN-BL-20102"],
    images: [],
    checkpoints: mkCp(),
    created_at: "2025-03-01T13:00:00Z",
  },
  {
    id: 4,
    product_id: 2,
    model: "WM1091SK",
    color: "Purple",
    batch_no: "B-WM1091P-002",
    production_date: "2025-03-01",
    inspection_date: "2025-03-01T14:30",
    qty_burning_in: 150,
    qty_produced: 150,
    qty_inspected: 150,
    qty_pass: 0,
    qty_fail: 35,
    qty_rework: 10,
    defect_rate: 23.33,
    defect_cat: "DC03",
    defect_loc: "Door frame",
    station: "Repair",
    overall_status: "fail",
    notes: "Dimensional defect – stop production",
    serial_numbers: ["SN-PU-10001", "SN-PU-10002"],
    images: [],
    checkpoints: mkCp("fail"),
    created_at: "2025-03-01T14:30:00Z",
  },
  {
    id: 6,
    product_id: 4,
    model: "WM891SK",
    color: "Pink",
    batch_no: "B-WM891P-001",
    production_date: "2025-03-01",
    inspection_date: "2025-03-01T09:00",
    qty_burning_in: 300,
    qty_produced: 300,
    qty_inspected: 300,
    qty_pass: 0,
    qty_fail: 9,
    qty_rework: 7,
    defect_rate: 3.0,
    defect_cat: "DC04",
    defect_loc: "Drum assembly",
    station: "Assembly",
    overall_status: "fail",
    notes: "Assembly check required",
    serial_numbers: ["SN-PK-40001"],
    images: [],
    checkpoints: mkCp(),
    created_at: "2025-03-01T09:00:00Z",
  },
  {
    id: 8,
    product_id: 4,
    model: "WM891SK",
    color: "Pink",
    batch_no: "B-WM891P-002",
    production_date: "2025-03-02",
    inspection_date: "2025-03-02T10:00",
    qty_burning_in: 300,
    qty_produced: 300,
    qty_inspected: 300,
    qty_pass: 0,
    qty_fail: 15,
    qty_rework: 8,
    defect_rate: 5.0,
    defect_cat: "DC02",
    defect_loc: "Front panel",
    station: "Repair",
    overall_status: "fail",
    notes: "Pink dye variation",
    serial_numbers: ["SN-PK-40101"],
    images: [],
    checkpoints: mkCp(),
    created_at: "2025-03-02T10:00:00Z",
  },
];

export const genNo = (id, date) =>
  "QC-" +
  new Date(date || Date.now()).getFullYear() +
  "-" +
  String(id).padStart(4, "0");
export const drColor = (r) => (r > 5 ? T.red : r > 2 ? T.yellow : T.blue);
