extend type Query {
  """
  ✨ Look up a single `DefectCategory` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  defectCategory(
    """
    The key used to identify the object.
    """
    key: DefectCategory_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: DefectCategory_FirstRow
  ): DefectCategory @fdc_generated(from: "DefectCategory", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `InspectionLog` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  inspectionLog(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: InspectionLog_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: InspectionLog_FirstRow
  ): InspectionLog @fdc_generated(from: "InspectionLog", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Product` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  product(
    """
    The key used to identify the object.
    """
    key: Product_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Product_FirstRow
  ): Product @fdc_generated(from: "Product", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `User` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  user(
    """
    The key used to identify the object.
    """
    key: User_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: User_FirstRow
  ): User @fdc_generated(from: "User", purpose: QUERY_SINGLE)
  """
  ✨ List `DefectCategory` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  defectCategories(
    """
    Filter condition to narrow down the query results.
    """
    where: DefectCategory_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [DefectCategory_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: DefectCategory_Having
  ): [DefectCategory!]! @fdc_generated(from: "DefectCategory", purpose: QUERY_MULTIPLE)
  """
  ✨ List `InspectionLog` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  inspectionLogs(
    """
    Filter condition to narrow down the query results.
    """
    where: InspectionLog_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [InspectionLog_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: InspectionLog_Having
  ): [InspectionLog!]! @fdc_generated(from: "InspectionLog", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Product` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  products(
    """
    Filter condition to narrow down the query results.
    """
    where: Product_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Product_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Product_Having
  ): [Product!]! @fdc_generated(from: "Product", purpose: QUERY_MULTIPLE)
  """
  ✨ List `User` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  users(
    """
    Filter condition to narrow down the query results.
    """
    where: User_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [User_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: User_Having
  ): [User!]! @fdc_generated(from: "User", purpose: QUERY_MULTIPLE)
}
